["protostar.config"]
protostar_version = "0.2.2"

["protostar.project"]
libs_path = "lib"

["protostar.build"]
cairo_path = ["./lib/cairo_contracts/src"]

["protostar.contracts"]
karma = [
    "./src/karma.cairo",
]
greed = [
    "./src/greed.cairo",
]

[profile.ci.protostar.shared_command_configs]
no_color=true
cairo_path = ["./lib/cairo_contracts/src"]
target = "contracts"