["protostar.config"]
protostar_version = "0.2.1"

["protostar.project"]
libs_path = "lib"

["protostar.shared_command_configs"]
cairo_path = ["./lib/cairo_contracts/src"]

["protostar.contracts"]
karma = [
    "./src/Karma.cairo",
]
greed = [
    "./src/Greed.cairo",
]
