["protostar.config"]
protostar_version = "0.2.6"

["protostar.project"]
libs_path = "lib"

["protostar.build"]
cairo_path = ["./lib/cairo_contracts/src"]

["protostar.contracts"]
greed = [
    "./src/modules/games/greed/Greed.cairo",
]
xoroshiro = [
    "./src/modules/utils/random/Xoroshiro128SS.cairo",
]
deadly_games = [
    "./src/DeadlyGames.cairo",
]
karma = [
    "./src/modules/token/Karma.cairo",
]
greed_mark = [
    "./src/modules/games/greed/GreedMark.cairo",
]
revolver = [
    "./src/modules/games/revolver/Revolver.cairo",
]

["protostar.shared_command_configs"]
no_color=true
cairo_path = ["./lib/cairo_contracts/src"]

[profile.devnet.protostar.deploy]
gateway_url="http://127.0.0.1:5050/"

[profile.testnet.protostar.deploy]
network="alpha-goerli"

[profile.mainnet.protostar.deploy]
network="alpha-mainnet"