["protostar.config"]
protostar_version = "0.2.2"

["protostar.project"]
libs_path = "lib"

["protostar.build"]
cairo_path = ["./lib/cairo_contracts/src"]

["protostar.contracts"]
karma = [
    "./src/karma.cairo",
]
greed = [
    "./src/greed.cairo",
]
deadly_games = [
    "./src/deadly_games.cairo",
]

[profile.ci.protostar.shared_command_configs]
no_color=true
cairo_path = ["./lib/cairo_contracts/src"]
target = "contracts"

[profile.devnet.protostar.deploy]
gateway_url="http://127.0.0.1:5050/"

[profile.testnet.protostar.deploy]
network="alpha-goerli"

[profile.mainnet.protostar.deploy]
network="alpha-mainnet"